Up-4520 - Polishes for deploy
35up/recommendations-slider pull request #18
Opened 2023-06-08 16:29 UTC by Drafter500

2023-06-09 07:51 UTC, enjoythelive1 requested changes

2023-06-09 07:51 UTC, enjoythelive1 commented on packages/react-slider/.npmrc
> +@35up:registry=https://registry.npmjs.org
This is only needed for yourt setup, because you have thids configured globally, instead of configuring by project. Please remove

2023-06-09 07:51 UTC, enjoythelive1 commented on packages/react-slider/src/reactify.tsx
>    // @ts-ignore
Couldn't we try to actually use the correct types?

2023-06-09 07:51 UTC, enjoythelive1 commented on packages/slider/.npmrc
> +@35up:registry=https://registry.npmjs.org
Remove

2023-06-12 08:53 UTC, enjoythelive1 approved these changes

2023-06-14 09:11 UTC, uschischroder approved these changes

2023-06-20 13:28 UTC, merged