UP-3731 - Implements first storybook test
35up/recommendations-slider pull request #19
Opened 2023-06-21 09:21 UTC by gustavoaz7

2023-06-22 11:30 UTC, enjoythelive1 requested changes
Why were these tests made for the react one instead of the actual component?

2023-06-22 11:30 UTC, enjoythelive1 commented on packages/react-slider/src/components/slider.stories.tsx
> +      .from(sliderEl.querySelectorAll('tfup-recommendation'));
This should not be needed for destructuring. NodeList implements iteration and any iterable can be deconstructed.
```suggestion
    const [
      firstReco,
      secondReco,
      thirdReco,
    ] = sliderEl.querySelectorAll('tfup-recommendation');
```

2023-06-22 11:30 UTC, enjoythelive1 commented on packages/slider/src/components/recommendations-slider/recommendations-slider.ts
> +          aria-label="arrow-left"
Besides a way to select the buttons, why?

2023-06-22 11:33 UTC, gustavoaz7 commented
> Why were these tests made for the react one instead of the actual component?

This is a PoC and I opted for what will most likely be used the most

2023-06-22 11:33 UTC, gustavoaz7 commented on packages/slider/src/components/recommendations-slider/recommendations-slider.ts
> +          aria-label="arrow-left"
Accessibility

2023-06-22 11:51 UTC, gustavoaz7 commented on packages/react-slider/src/components/slider.stories.tsx
> +      .from(sliderEl.querySelectorAll('tfup-recommendation'));
> Type 'NodeListOf<Recommendation>' is not an array type.ts(2461)

2023-06-22 12:20 UTC, enjoythelive1 commented on packages/react-slider/src/components/slider.stories.tsx
> +      .from(sliderEl.querySelectorAll('tfup-recommendation'));
This must be because of the compilation target. I guess its ok

2023-06-22 12:21 UTC, enjoythelive1 approved these changes

2023-06-26 11:54 UTC, Drafter500 commented on packages/react-slider/src/components/slider.stories.tsx
> +    await step('Slide right twice', async () => {
so each next test depends on the previous one?

2023-06-26 12:04 UTC, Drafter500 approved these changes
The code looks fine to me, but I could not tell is its useful?
@gustavoaz7 What are your thoughts on it? Did you like it, the API, and the structure? Do you see real benefits? 

Btw, When running locally I get this error `Cannot read properties of null (reading 'click')` and the test fails, do you have a clue?

2023-06-26 12:06 UTC, enjoythelive1 commented
> The code looks fine to me, but I could not tell is its useful? @gustavoaz7 What are your thoughts on it? Did you like it, the API, and the structure? Do you see real benefits?
> 
> Btw, When running locally I get this error `Cannot read properties of null (reading 'click')` and the test fails, do you have a clue?

I see this is useffull as it could replace the test we have in the slider about testing this specific behavior. The cypress test setup is hacky and complicated. It would be easier to run these tests in the command line.

2023-06-26 12:13 UTC, gustavoaz7 commented on packages/react-slider/src/components/slider.stories.tsx
> +    await step('Slide right twice', async () => {
"test" is the whole `play` function. `step`s are just used to group interactions (https://storybook.js.org/docs/react/writing-tests/interaction-testing#group-interactions-with-the-step-function). It also makes the test output cleaner in storybook

2023-06-26 12:17 UTC, enjoythelive1 commented
Also, in web compoenents. It would be a better test platform for web components. As we could see the behavior in storybook and also have the tests run in a real browser environmet. But that would also make tests more expensive.

We could use it as part of what we show in stories, as a way to showcase behavior of components (like dropdown opening) or an input being used.

2023-06-30 02:14 UTC, uschischroder approved these changes

2023-06-30 08:34 UTC, Drafter500 approved these changes

2023-06-30 09:10 UTC, merged