UP-4809 - Adds acceptance tests
35up/recommendations-slider pull request #20
Opened 2023-07-07 11:55 UTC by enjoythelive1

2023-07-07 15:29 UTC, Drafter500 commented on tests-acceptance/package.json
> +    "test-acceptance": "server-test 'npx vite --port 3000' localhost:3000 cy:run",
```suggestion
    "test-acceptance": "server-test 'nom run vite --port 3000' localhost:3000 cy:run",
```
vite is already installed as dependency

2023-07-07 16:02 UTC, enjoythelive1 commented on tests-acceptance/package.json
> +    "test-acceptance": "server-test 'npx vite --port 3000' localhost:3000 cy:run",
`npm run` only runs scripts defined in `package.json`. `npx` allows you to run scripts installed by the dependencies you have installed.

2023-07-07 16:02 UTC, Drafter500 commented on tests-acceptance/package.json
> +    "@35up/js-sdk-browser": "^1.0.0",
this references the npm registry, and lerna bootstrap did not create a symlink for me for some reason, does it create a symlink for you?

2023-07-07 16:04 UTC, Drafter500 requested changes
The react slider test fails for me:
```
  1) @35up/react-recommendations-slider
       is properly bundled without dangling dependencies:
     TypeError: The following error originated from your application code, not from Cypress.

  > Cannot read properties of null (reading 'useMemo')
  1) @35up/react-recommendations-slider
       is properly bundled without dangling dependencies:
     TypeError: The following error originated from your application code, not from Cypress.

  > Cannot read properties of null (reading 'useMemo')
```
Seems like references are broken. In fact symlinks are not working, so you may use `file:../` instead

2023-07-07 16:05 UTC, Drafter500 commented on tests-acceptance/tests/bundle.spec.js
> +  it('is properly bundled without dangling dependencies', () => {
what means dangling dependencies here and how is this being checked?

2023-07-07 16:44 UTC, enjoythelive1 commented on tests-acceptance/package.json
> +    "@35up/js-sdk-browser": "^1.0.0",
This is not in the monorepo. So it should download it form the npm registry.

2023-07-07 16:45 UTC, enjoythelive1 commented
> The react slider test fails for me:
> 
> ```
>   1) @35up/react-recommendations-slider
>        is properly bundled without dangling dependencies:
>      TypeError: The following error originated from your application code, not from Cypress.
> 
>   > Cannot read properties of null (reading 'useMemo')
>   1) @35up/react-recommendations-slider
>        is properly bundled without dangling dependencies:
>      TypeError: The following error originated from your application code, not from Cypress.
> 
>   > Cannot read properties of null (reading 'useMemo')
> ```
> 
> Seems like references are broken. In fact symlinks are not working, so you may use `file:../` instead

You need to build react-slider locally. Previous build was bundling everythign, including react.

2023-07-07 16:45 UTC, enjoythelive1 commented on tests-acceptance/tests/bundle.spec.js
> +  it('is properly bundled without dangling dependencies', () => {
I copypasted the description. Will change.

2023-07-07 16:56 UTC, Drafter500 commented
> > The react slider test fails for me:
> > ```
> >   1) @35up/react-recommendations-slider
> >        is properly bundled without dangling dependencies:
> >      TypeError: The following error originated from your application code, not from Cypress.
> > 
> >   > Cannot read properties of null (reading 'useMemo')
> >   1) @35up/react-recommendations-slider
> >        is properly bundled without dangling dependencies:
> >      TypeError: The following error originated from your application code, not from Cypress.
> > 
> >   > Cannot read properties of null (reading 'useMemo')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Seems like references are broken. In fact symlinks are not working, so you may use `file:../` instead
> 
> You need to build react-slider locally. Previous build was bundling everythign, including react.

I did that in the beginning

2023-07-07 16:58 UTC, Drafter500 commented on tests-acceptance/package.json
> +    "@35up/js-sdk-browser": "^1.0.0",
I actually meant `@35up/recommendations-slider`,
but then the test will run against latest published package and not the current one

2023-07-07 17:10 UTC, Drafter500 commented on .github/workflows/ci-acceptance-tests.yml
> +      - ./.github/workflows/acceptance-tests.yml
```suggestion
      - ./.github/workflows/ci-acceptance-tests.yml
```
and below too

2023-07-07 17:25 UTC, Drafter500 commented on tests-acceptance/package.json
> +    "react": "^17.0.2",
I updated this and react-dom to v18 and the issue was fixed. It happened because the lib was using version 18 so we ended up having 2 versions of react which were conflicting

2023-07-10 07:57 UTC, enjoythelive1 commented on tests-acceptance/package.json
> +    "react": "^17.0.2",
The lib was not using a specificversion, as we don'T use package-lock on the libraries. And the other uses of react in the repo are react 17.

2023-07-10 08:01 UTC, enjoythelive1 commented on tests-acceptance/package.json
> +    "react": "^17.0.2",
What I am saying is that this issue is depending in your local configuration

2023-07-12 09:28 UTC, Drafter500 approved these changes

2023-07-12 09:46 UTC, uschischroder approved these changes

2023-07-12 09:51 UTC, merged